# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b3a610bb0cf454ea721b2fb2b4d2bbb28ed5ebd6030381338091decdfb8a98ad84e7cd760ce6125617b665742b53a357a6baa744085b8091d3536f9391d470

test:
  secret_key_base: 399aa0ab8b51fc2243ecc38558e9d69f7fb3d3e336a1262a117d789ecb052805f97d1492dfa59f59c2986aaa852ed678609510c47c173c1cbeef2e01b645e5c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
